name: music_player
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  crypto: ^3.0.6
  file_picker: ^8.1.7
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.3.1
  lucide_icons_flutter: ^3.1.14
  metadata_god: ^0.5.0
  path: ^1.9.0
  path_provider: ^2.1.5
  sqlite3: ^2.7.5
  sqlite3_flutter_libs: ^0.5.0
  window_manager: ^0.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
