name: music_player
description: "waveCatcher — desktop music player."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  crypto: ^3.0.6
  file_picker: ^8.1.7
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  flutter_riverpod: ^3.3.1
  http: ^1.6.0
  lucide_icons_flutter: ^3.1.14
  media_kit: ^1.2.6
  media_kit_libs_audio: ^1.0.7
  metadata_god: ^0.5.0
  path: ^1.9.0
  path_provider: ^2.1.5
  sqlite3: ^2.7.5
  sqlite3_flutter_libs: ^0.5.0
  window_manager: ^0.4.3
  windows1251: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true
